/**
 * catalogSeed.ts — static list of common Norwegian groceries used to seed the item catalog.
 *
 * Exports CATALOG_SEED, ~230 real-world grocery/household items each tagged with
 * a shopping category key and a realistic Norwegian price (NOK). useCatalogStore
 * inserts these into the store_items table on first run to power autocomplete and
 * auto-categorisation, and backfills prices for any rows previously seeded without one.
 *
 * Connections:
 *   Imports → —
 *   Used by → store/useCatalogStore.ts
 *   Data    → seeds the `store_items` SQLite table (via useCatalogStore)
 *
 * Edit notes:
 *   - `category` values must match the shopping category keys (produce, dairy,
 *     meat, fish, bread, frozen, canned, dry, snacks, drinks, cleaning, personal).
 *   - Item names are intentionally Norwegian and NOT translated — only UI follows the user's language.
 *   - Prices are approximate typical NOK retail prices and will be overwritten once
 *     the user records an actual purchase via the scan/shopping flow.
 */
export type SeedItem = { name: string; category: string; price: number };

export const CATALOG_SEED: SeedItem[] = [
  // Frukt og grønt
  { name: 'Epler', category: 'produce', price: 32.90 },
  { name: 'Appelsiner', category: 'produce', price: 34.90 },
  { name: 'Sitroner', category: 'produce', price: 19.90 },
  { name: 'Pærer', category: 'produce', price: 34.90 },
  { name: 'Druer', category: 'produce', price: 39.90 },
  { name: 'Jordbær', category: 'produce', price: 39.90 },
  { name: 'Blåbær', category: 'produce', price: 34.90 },
  { name: 'Bringebær', category: 'produce', price: 34.90 },
  { name: 'Mango', category: 'produce', price: 19.90 },
  { name: 'Ananas', category: 'produce', price: 29.90 },
  { name: 'Kiwi', category: 'produce', price: 19.90 },
  { name: 'Tomater', category: 'produce', price: 29.90 },
  { name: 'Cherrytomater', category: 'produce', price: 29.90 },
  { name: 'Agurk', category: 'produce', price: 14.90 },
  { name: 'Paprika rød', category: 'produce', price: 19.90 },
  { name: 'Paprika gul', category: 'produce', price: 19.90 },
  { name: 'Paprika grønn', category: 'produce', price: 14.90 },
  { name: 'Rødløk', category: 'produce', price: 14.90 },
  { name: 'Hvitløk', category: 'produce', price: 14.90 },
  { name: 'Brokkoli', category: 'produce', price: 24.90 },
  { name: 'Salat', category: 'produce', price: 19.90 },
  { name: 'Spinat', category: 'produce', price: 24.90 },
  { name: 'Purre', category: 'produce', price: 19.90 },
  { name: 'Potet', category: 'produce', price: 29.90 },
  { name: 'Søtpotet', category: 'produce', price: 24.90 },
  { name: 'Sopp', category: 'produce', price: 24.90 },
  { name: 'Chili', category: 'produce', price: 14.90 },
  { name: 'Ingefær', category: 'produce', price: 14.90 },
  { name: 'Mais', category: 'produce', price: 14.90 },
  { name: 'Squash', category: 'produce', price: 19.90 },
  { name: 'Fennikel', category: 'produce', price: 24.90 },
  // REMA 1000 additions
  { name: 'Aubergine Løsvekt', category: 'produce', price: 58.44 },
  { name: 'Gulrot 15x1 Kg Prima', category: 'produce', price: 18.90 },
  { name: 'Stangselleri', category: 'produce', price: 24.90 },

  // Meieri
  { name: 'Helmelk 1L', category: 'dairy', price: 26.90 },
  { name: 'Lettmelk 1L', category: 'dairy', price: 24.90 },
  { name: 'Ekstra lettmelk 1L', category: 'dairy', price: 24.90 },
  { name: 'H-melk 1L', category: 'dairy', price: 24.90 },
  { name: 'Kremfløte', category: 'dairy', price: 34.90 },
  { name: 'Matfløte', category: 'dairy', price: 29.90 },
  { name: 'Rømme', category: 'dairy', price: 27.90 },
  { name: 'Crème fraîche', category: 'dairy', price: 29.90 },
  { name: 'Kulturmelk', category: 'dairy', price: 22.90 },
  { name: 'Kefir', category: 'dairy', price: 24.90 },
  { name: 'Yoghurt naturell', category: 'dairy', price: 22.90 },
  { name: 'Gresk yoghurt', category: 'dairy', price: 29.90 },
  { name: 'Kvarg', category: 'dairy', price: 27.90 },
  { name: 'Smør', category: 'dairy', price: 49.90 },
  { name: 'Margarin', category: 'dairy', price: 34.90 },
  { name: 'Norvegia', category: 'dairy', price: 54.90 },
  { name: 'Jarlsberg', category: 'dairy', price: 59.90 },
  { name: 'Hvitost skivet', category: 'dairy', price: 44.90 },
  { name: 'Gudbrandsdalsost', category: 'dairy', price: 54.90 },
  { name: 'Brunost', category: 'dairy', price: 39.90 },
  { name: 'Fløtemysost', category: 'dairy', price: 44.90 },
  { name: 'Cheddar', category: 'dairy', price: 54.90 },
  { name: 'Brie', category: 'dairy', price: 64.90 },
  // REMA 1000 additions
  { name: 'Cottage Cheese Mager 770g Tine', category: 'dairy', price: 46.90 },
  { name: 'Egg 18pk M Prima Lavpris', category: 'dairy', price: 59.90 },
  { name: 'Litago Sjokolademelk 1L Tine', category: 'dairy', price: 32.90 },
  { name: 'Meierismør 500g Tine', category: 'dairy', price: 61.40 },
  { name: 'Mozzarella Revet 22% 180g R', category: 'dairy', price: 37.90 },
  { name: 'Parmigiano Reggiano Revet 80g', category: 'dairy', price: 42.50 },
  { name: 'Q Helmelk 3.7% (1.75 L)', category: 'dairy', price: 40.90 },
  { name: 'Skinkeost 175g Tube Kavli', category: 'dairy', price: 35.90 },
  { name: 'Skyr Mini Banan Pose (90 g)', category: 'dairy', price: 15.90 },
  { name: 'Skyr Mini Br.bær Pose (90 g)', category: 'dairy', price: 15.90 },
  { name: 'Tine Yoghurt Kirsebær (500 g)', category: 'dairy', price: 25.40 },
  { name: 'Tine Yoghurt Vanilje (500 g)', category: 'dairy', price: 23.90 },
  { name: 'Yoghurt Vanilje Gresk Type 730G Tine', category: 'dairy', price: 49.90 },

  // Kjøtt
  { name: 'Kyllingfilet', category: 'meat', price: 99.90 },
  { name: 'Kyllinglår', category: 'meat', price: 79.90 },
  { name: 'Kjøttdeig storfe 400g', category: 'meat', price: 74.90 },
  { name: 'Lammekjøtt', category: 'meat', price: 149.90 },
  { name: 'Svinekotelett', category: 'meat', price: 79.90 },
  { name: 'Svinefilet', category: 'meat', price: 89.90 },
  { name: 'Ribbe', category: 'meat', price: 119.90 },
  { name: 'Bacon skivet', category: 'meat', price: 59.90 },
  { name: 'Grillpølser', category: 'meat', price: 49.90 },
  { name: 'Medisterpølse', category: 'meat', price: 59.90 },
  { name: 'Kjøttkaker', category: 'meat', price: 64.90 },
  { name: 'Karbonader', category: 'meat', price: 64.90 },
  { name: 'Leverpostei', category: 'meat', price: 34.90 },
  { name: 'Skinke skivet', category: 'meat', price: 44.90 },
  { name: 'Salami', category: 'meat', price: 49.90 },
  // REMA 1000 additions
  { name: 'Hamburgerrygg 150g Nordfjord', category: 'meat', price: 24.90 },
  { name: 'Kokt Skinke 150g Nordfjord', category: 'meat', price: 24.90 },
  { name: 'Kyllingkjøttdeig 400G Solvinge', category: 'meat', price: 59.90 },
  { name: 'Paprikaskinke 220g (Nordfjord)', category: 'meat', price: 42.50 },
  { name: 'Prima Lavpris 400 G (Kyllingkjøttdeig)', category: 'meat', price: 64.90 },
  { name: 'Svinekjøttdeig 20% 300G', category: 'meat', price: 31.90 },

  // Fisk
  { name: 'Laksefilet', category: 'fish', price: 119.90 },
  { name: 'Torskefilet', category: 'fish', price: 99.90 },
  { name: 'Ørretfilet', category: 'fish', price: 89.90 },
  { name: 'Sei filet', category: 'fish', price: 79.90 },
  { name: 'Reker', category: 'fish', price: 109.90 },
  { name: 'Tunfisk i vann', category: 'fish', price: 22.90 },
  { name: 'Makrell i tomat', category: 'fish', price: 19.90 },
  { name: 'Sild i lake', category: 'fish', price: 29.90 },
  { name: 'Fiskepinner', category: 'fish', price: 59.90 },
  { name: 'Klippfisk', category: 'fish', price: 139.90 },
  // REMA 1000 additions
  { name: 'Rotfrukter M/laks 8m 190g Nestle', category: 'fish', price: 24.90 },

  // Brød og bakst
  { name: 'Grovbrød', category: 'bread', price: 34.90 },
  { name: 'Loff', category: 'bread', price: 29.90 },
  { name: 'Kneippbrød', category: 'bread', price: 34.90 },
  { name: 'Rugbrød', category: 'bread', price: 39.90 },
  { name: 'Surdeigsbrød', category: 'bread', price: 49.90 },
  { name: 'Rundstykker', category: 'bread', price: 29.90 },
  { name: 'Bagett', category: 'bread', price: 19.90 },
  { name: 'Pitabrød', category: 'bread', price: 29.90 },
  { name: 'Tortilla hvete', category: 'bread', price: 34.90 },
  { name: 'Tortilla fullkorn', category: 'bread', price: 34.90 },
  { name: 'Hamburgerbrød', category: 'bread', price: 29.90 },
  { name: 'Hotdogbrød', category: 'bread', price: 24.90 },
  { name: 'Knekkebrød', category: 'bread', price: 39.90 },
  { name: 'Kavring', category: 'bread', price: 39.90 },
  { name: 'Flatbrød', category: 'bread', price: 34.90 },
  // REMA 1000 additions
  { name: 'Bondebrød Bergen 750g Mb (Mesterbakeren)', category: 'bread', price: 51.90 },
  { name: 'Brioche Burgerbrød 4pk (Mesterbakeren)', category: 'bread', price: 38.90 },
  { name: 'G&G Proteinbrød Fryst 720G', category: 'bread', price: 55.90 },
  { name: 'Grovbrød Fryst 660g Superhelt', category: 'bread', price: 39.90 },
  { name: 'Skoleboller 2Pk (250 G)', category: 'bread', price: 42.90 },

  // Frysevarer
  { name: 'Grandiosa pizza', category: 'frozen', price: 79.90 },
  { name: 'Frosne erter', category: 'frozen', price: 24.90 },
  { name: 'Frosne bønner', category: 'frozen', price: 24.90 },
  { name: 'Frosne blandede grønnsaker', category: 'frozen', price: 29.90 },
  { name: 'Frosne spinat', category: 'frozen', price: 24.90 },
  { name: 'Frosne blåbær', category: 'frozen', price: 39.90 },
  { name: 'Frosne jordbær', category: 'frozen', price: 34.90 },
  { name: 'Pommes frites', category: 'frozen', price: 39.90 },
  { name: 'Vafler', category: 'frozen', price: 49.90 },
  { name: 'Iskrem vanilje', category: 'frozen', price: 69.90 },
  // REMA 1000 additions
  { name: 'Isbitposer 20-pack', category: 'frozen', price: 28.90 },

  // Hermetikk
  { name: 'Hakkede tomater', category: 'canned', price: 14.90 },
  { name: 'Tomatpuré', category: 'canned', price: 19.90 },
  { name: 'Kokosmelk', category: 'canned', price: 19.90 },
  { name: 'Kikerter', category: 'canned', price: 14.90 },
  { name: 'Kidneybønner', category: 'canned', price: 14.90 },
  { name: 'Hvite bønner', category: 'canned', price: 14.90 },
  { name: 'Linser', category: 'canned', price: 14.90 },
  { name: 'Mais på boks', category: 'canned', price: 14.90 },
  { name: 'Ananas biter', category: 'canned', price: 19.90 },
  { name: 'Oliven grønne', category: 'canned', price: 24.90 },
  { name: 'Oliven sorte', category: 'canned', price: 24.90 },
  // REMA 1000 additions
  { name: 'Lasagne 200g (Toro)', category: 'canned', price: 39.90 },
  { name: 'Meksikansk Gryte 189g (Toro)', category: 'canned', price: 36.90 },
  { name: 'Tomater Finhakkede 400g Petti', category: 'canned', price: 20.90 },
  { name: 'Tomatpurè 180g Stavland', category: 'canned', price: 19.90 },
  { name: 'Tomatpuré 140g', category: 'canned', price: 8.90 },

  // Tørrmat
  { name: 'Spaghetti', category: 'dry', price: 19.90 },
  { name: 'Penne', category: 'dry', price: 19.90 },
  { name: 'Fusilli', category: 'dry', price: 19.90 },
  { name: 'Ris langkornet', category: 'dry', price: 24.90 },
  { name: 'Basmatiris', category: 'dry', price: 34.90 },
  { name: 'Müsli', category: 'dry', price: 44.90 },
  { name: 'Cornflakes', category: 'dry', price: 39.90 },
  { name: 'Hvetemel', category: 'dry', price: 19.90 },
  { name: 'Grovt mel', category: 'dry', price: 22.90 },
  { name: 'Brunt sukker', category: 'dry', price: 29.90 },
  { name: 'Havsalt', category: 'dry', price: 24.90 },
  { name: 'Pepper', category: 'dry', price: 29.90 },
  { name: 'Paprikapulver', category: 'dry', price: 29.90 },
  { name: 'Karri', category: 'dry', price: 29.90 },
  { name: 'Oregano', category: 'dry', price: 24.90 },
  { name: 'Basilikum', category: 'dry', price: 24.90 },
  { name: 'Timian', category: 'dry', price: 24.90 },
  { name: 'Olivenolje', category: 'dry', price: 59.90 },
  { name: 'Rapsolje', category: 'dry', price: 39.90 },
  { name: 'Soyasaus', category: 'dry', price: 34.90 },
  { name: 'Ketchup', category: 'dry', price: 29.90 },
  { name: 'Honning', category: 'dry', price: 59.90 },
  { name: 'Syltetøy jordbær', category: 'dry', price: 39.90 },
  { name: 'Peanøttsmør', category: 'dry', price: 49.90 },
  { name: 'Nutella', category: 'dry', price: 59.90 },
  { name: 'Kaffe malt', category: 'dry', price: 89.90 },
  { name: 'Kaffe filterkokt', category: 'dry', price: 99.90 },
  { name: 'Instant kaffe', category: 'dry', price: 79.90 },
  { name: 'Svart te', category: 'dry', price: 49.90 },
  { name: 'Grønn te', category: 'dry', price: 49.90 },
  { name: 'Kakao', category: 'dry', price: 44.90 },
  { name: 'Bakepulver', category: 'dry', price: 19.90 },
  // REMA 1000 additions
  { name: 'Ekte Majones 330g (Mills)', category: 'dry', price: 36.90 },
  { name: 'Flerkornsgrøt Eple/Fersken 8m (Semper 120g)', category: 'dry', price: 18.90 },
  { name: 'Grøt Eple & Fersken 6m (Semper 120g)', category: 'dry', price: 18.90 },
  { name: 'Grøt Pære & Aprikos 6m (Semper 120g)', category: 'dry', price: 24.90 },
  { name: 'Havregranola Naturell 4-korn Urkraft (430 G)', category: 'dry', price: 42.00 },
  { name: 'Havregryn Lettkokte 1.2kg Urkraft', category: 'dry', price: 21.90 },
  { name: 'Håndsåpe Harmoni 500ML R', category: 'dry', price: 19.90 },
  { name: 'Kanel Malt 67g Toro', category: 'dry', price: 21.10 },
  { name: 'Kardemomme 46g Toro', category: 'dry', price: 35.90 },
  { name: 'Lasagne Plater 500g Barilla', category: 'dry', price: 41.90 },
  { name: 'Maggi Klar Oksekraft 500Ml', category: 'dry', price: 55.40 },
  { name: 'Melis 500g Dansukker', category: 'dry', price: 21.30 },
  { name: 'Sennep Dijon Original 380g', category: 'dry', price: 29.90 },
  { name: 'Sukker 1Kg Dansukker', category: 'dry', price: 35.90 },
  { name: 'Sweet Baby Rays Barbecue Sauce 510g', category: 'dry', price: 46.90 },
  { name: 'Taco Sauce Hot 230g Santa Maria', category: 'dry', price: 20.40 },
  { name: 'Taco Spice Mix R', category: 'dry', price: 11.00 },
  { name: 'Tørrgjær Original 65g Idun (5 Pos)', category: 'dry', price: 19.40 },
  { name: 'Urt Koriander 6X15g Flow Vikin', category: 'dry', price: 16.00 },
  { name: 'Worcester Sauce 150ml (Heinz)', category: 'dry', price: 37.40 },

  // Snacks
  { name: 'Potetgull', category: 'snacks', price: 39.90 },
  { name: 'Popcorn', category: 'snacks', price: 29.90 },
  { name: 'Mandler', category: 'snacks', price: 49.90 },
  { name: 'Valnøtter', category: 'snacks', price: 59.90 },
  { name: 'Smørnøtter', category: 'snacks', price: 44.90 },
  { name: 'Pistasjenøtter', category: 'snacks', price: 64.90 },
  { name: 'Rosiner', category: 'snacks', price: 24.90 },
  { name: 'Freia melkesjokolade', category: 'snacks', price: 29.90 },
  { name: 'Kvikk Lunsj', category: 'snacks', price: 19.90 },
  { name: 'Daim', category: 'snacks', price: 34.90 },
  { name: 'KitKat', category: 'snacks', price: 19.90 },
  { name: 'Digestive kjeks', category: 'snacks', price: 34.90 },
  { name: 'Ritz kjeks', category: 'snacks', price: 34.90 },
  { name: 'Lakrisflik', category: 'snacks', price: 24.90 },
  { name: 'Twist', category: 'snacks', price: 79.90 },
  // REMA 1000 additions
  { name: 'Cashewnøtter 175g', category: 'snacks', price: 31.40 },
  { name: 'Nacho Chips 185g Santa Maria', category: 'snacks', price: 26.90 },
  { name: 'Stratos Helt Sprøtt 150g', category: 'snacks', price: 29.90 },

  // Drikke
  { name: 'Appelsinjuice', category: 'drinks', price: 29.90 },
  { name: 'Eplejuice', category: 'drinks', price: 29.90 },
  { name: 'Smoothie', category: 'drinks', price: 39.90 },
  { name: 'Farris', category: 'drinks', price: 22.90 },
  { name: 'Imsdal', category: 'drinks', price: 19.90 },
  { name: 'Pepsi Max', category: 'drinks', price: 29.90 },
  { name: 'Sprite', category: 'drinks', price: 29.90 },
  { name: 'Saft solbær', category: 'drinks', price: 34.90 },
  { name: 'Saft lime', category: 'drinks', price: 34.90 },
  { name: 'Iste', category: 'drinks', price: 24.90 },
  { name: 'Lettøl', category: 'drinks', price: 19.90 },
  // REMA 1000 additions
  { name: 'Bare Øl 0.5L 6-pack', category: 'drinks', price: 157.20 },
  { name: 'Burn Original 500ml Bx', category: 'drinks', price: 30.40 },
  { name: 'Coca-Cola 1.5L', category: 'drinks', price: 31.90 },
  { name: 'Coca-Cola 330Ml Sleek X 10Pk Bx', category: 'drinks', price: 89.00 },
  { name: 'Fanta Exotic 1,5L Plastfl', category: 'drinks', price: 34.90 },
  { name: 'Iskaffe Cappuccino 330ml', category: 'drinks', price: 19.90 },
  { name: 'Iskaffe Salty Caramel Uten 330ml', category: 'drinks', price: 19.90 },
  { name: 'Monster Aussie Lemonade 500Ml Bx', category: 'drinks', price: 26.90 },
  { name: 'Monster Ultra White 500ml', category: 'drinks', price: 25.90 },
  { name: 'Mozell Drue & Eple Light 1.5L', category: 'drinks', price: 37.90 },
  { name: 'Solo Super 1.5L', category: 'drinks', price: 24.90 },

  // Rengjøring
  { name: 'Toalettpapir', category: 'cleaning', price: 79.90 },
  { name: 'Kjøkkenrull', category: 'cleaning', price: 44.90 },
  { name: 'Husholdningsfilm', category: 'cleaning', price: 29.90 },
  { name: 'Aluminiumsfolie', category: 'cleaning', price: 29.90 },
  { name: 'Bakepapir', category: 'cleaning', price: 24.90 },
  { name: 'Søppelposer 10L', category: 'cleaning', price: 34.90 },
  { name: 'Søppelposer 20L', category: 'cleaning', price: 39.90 },
  { name: 'Søppelposer 120L', category: 'cleaning', price: 49.90 },
  { name: 'Vaskemiddel', category: 'cleaning', price: 99.90 },
  { name: 'Tøymykner', category: 'cleaning', price: 79.90 },
  { name: 'Oppvaskmiddel', category: 'cleaning', price: 39.90 },
  { name: 'Oppvasktabletter', category: 'cleaning', price: 89.90 },
  { name: 'Allrengjøring', category: 'cleaning', price: 59.90 },
  { name: 'Toalettrens', category: 'cleaning', price: 49.90 },
  { name: 'Gulvvask', category: 'cleaning', price: 59.90 },
  { name: 'Svamp', category: 'cleaning', price: 24.90 },
  { name: 'Stearinlys', category: 'cleaning', price: 39.90 },
  { name: 'Strikkeposer (frysebagger)', category: 'cleaning', price: 29.90 },
  // REMA 1000 additions
  { name: 'Kjøkkenpapir 6-pack', category: 'cleaning', price: 59.50 },
  { name: 'Mikrofiberklut Universal', category: 'cleaning', price: 19.90 },
  { name: 'Toalettpapir 24PK R', category: 'cleaning', price: 79.90 },

  // Personlig pleie
  { name: 'Sjampo', category: 'personal', price: 59.90 },
  { name: 'Balsam', category: 'personal', price: 59.90 },
  { name: 'Deodorant', category: 'personal', price: 64.90 },
  { name: 'Munnvann', category: 'personal', price: 54.90 },
  { name: 'Barberskum', category: 'personal', price: 39.90 },
  { name: 'Ansiktskrem', category: 'personal', price: 89.90 },
  { name: 'Body lotion', category: 'personal', price: 79.90 },
  { name: 'Solkrem SPF 30', category: 'personal', price: 119.90 },
  { name: 'Bind', category: 'personal', price: 54.90 },
  { name: 'Tamponger', category: 'personal', price: 59.90 },
  { name: 'Bleier', category: 'personal', price: 149.90 },
  { name: 'Bleietørk', category: 'personal', price: 64.90 },
  { name: 'Plaster', category: 'personal', price: 39.90 },
  { name: 'Paracet', category: 'personal', price: 64.90 },
  { name: 'Ibux', category: 'personal', price: 69.90 },
  { name: 'Vitaminer', category: 'personal', price: 119.90 },
  { name: 'Q-tips', category: 'personal', price: 29.90 },
  // REMA 1000 additions
  { name: 'Colgate Sensation White Tannkrem 75ml', category: 'personal', price: 27.90 },
  { name: 'Libero Comfort Str 5 (24 Stk)', category: 'personal', price: 71.90 },
  { name: 'Libero Comfort Str 6 22 Stk', category: 'personal', price: 70.50 },
  { name: 'Mild Trippel Dusj 220ml Asan', category: 'personal', price: 26.90 },
  { name: 'Otrivin Voksne Mentol 1mg/ml', category: 'personal', price: 79.90 },
  { name: 'Tannbørste Step 1 Baby', category: 'personal', price: 27.90 },
  { name: 'Tanntråd 2 I 1 Flosser R (32 Stk)', category: 'personal', price: 19.90 },
];
